### ISSUE TITLE
Add time-tracking to state management

### ISSUE THREAD

**Issue by oubiwann** [cmr-exchange/dev-env-manager#12]
* ~Create a namespace that won't get reloaded~
* [x] Define atoms for holding time data:
  * ~service start times~  (moved to #10)
  * [x] system start times
  * ~service stop times~  (moved to #10)
  * [x] system stop times
* [x] Define convenience functions for extracting data
  * [x] Get last start/stop/restart time
  * ~Get average start/stop/restart time~

Depends upon: #10, #11
